language: java
jdk:
  - oraclejdk8

env:
  global:
    - secure: "JA1XGliMbw370X96ukGrvnBDzYQxlOxUo/Scff4VQyq+7sdCCXTQpbjpl28kri08QPt0WS9qcLHnOmcZiq62YUIDuNQAk2kIoki/DO4M9b86UgOHLb5MTYDxYIbOCJlZdl3TUEd2tUIJ0xM7AIRe8kHXUNhNxEjsm+qab23OSK/gZrzLwcWhCQfenE9uedL9xUeJI5SorJ/F12X65f014bVsniym2QXlFiOWvRaZnGWCfYxU9xWl9wSastFCzMsUTGqeRXftp5kfof6Y6KtDbkUSBbcbHdb4wv4g14g7GYd4dkza4CelmKoLbV5H2xjMOzHR/6NDQ8azSv5j5TRD4uBcdBr5rBJSowWEymjw66ZhSTYYRfYYnE1cQhLrGVT2XoUPmCY5PzSYdRkCA/kZdnJPxb+wdMgfdx3FE67wHm6M7uWOW9Smdy+qwNx3T4Fdp75lrxkuLK6Thtk/fGhs1g4lEsXD+YXgIdZjnj8Go2GxdiEQCIJovJRWDkp6+C/BjS9nbVBHtZ36FR73NELV7R6dAZNmiXbrxI3YfqKTvIg6OGbiR7EQ8WATsnMmMtvRyPi1kEj8sulhtg95WkVjYkWUiERv8HTGbjpPZEVQ+q9+3CJzmwmcmImDS60eXAr84R011AkG/YccrP20x/27UlKO7PtGiu8a0awesAzQmVs="
    - # ^^ OSSRH_JIRA_USERNAME
    - secure: "kilIEz+jutUflyosc42CoxD1G9J9c1nYyXWnz3K3Z4BeYFb+y8YbYDjP1WmeCFVzFfjN8UuLQdMc74Z2QTVgQpFfFx0p6uQtBVR3uonKNZuIemeEz+c/ILEu7MAhOAoytoEnsNyx4foNyNqvFehHbe7JbIuh1jathBfnwHotvlxvE5GwetpvOAH/GkUFb8U8sIhlwhUGsVkPkB0EPBxO9MyzGMi7QqgdzprTKyDCZKBGJUqJ8hWJHwwxmO8XdLbPh/xiIe0/lj0rEiHRRMI84nuxdaq7kqg2ymvh8RF55yecuQbRz4dEPUMb42j+wzcNumF/0MyG29SCPwX3xQu9iLI5/nMTBB4yd939ejILXrdRk62dUkdQyqafcq1+BrsVOEeXEKEN7Yvz0WjiIhRMF5E3MwoQLyFqhZGW6JJ2sBvP2XSjpQ3NfKrq6yEzF6fkaU7eYG5m90UJzkmS26/S40HBATcYPkbhVB+NmmXfpk2ms17YJqY5B+giS1j59eUkq+WLrz49N062kzbtHIfDodopsYT0clxfa8qMX/a5MdC/Vg0OVmpgt8e5dVztIwSEgSw0Pxy9se020hp4S/p6FIGhvvhNS0r7NwFM/BISRxEWfq5SmntgE8MOhXChS2AUpE7e/2IE9Drf2HpEiE/K7lOALz5hSMyjDvDdMTP6KiQ="
    - # ^^ OSSRH_JIRA_PASSWORD
    - secure: "NcP4RTuUEXPaZJbwaE3OvpP5B37f3ck+0ORT4SrExF2FZ8Tlzp9nFg29ao7NWgkT3haf7EZUvzKO3aBN3YqgnnZQrpybQsJ2ITx5d6UIKSisDxdmQ76aTyA5Qo2aQiRF6/34CMWydscg//KtNjv7RI0Mtg3VPpiSrb5Z8O/9yMS0Tti4znRCZmzKPNDqkWeG5dSgzCskXQFAFXekjA3sn+4SQ4LbVegQOqNSZTpE5mdvBIJ6D3ZquhjJIY8X/xPHhQrl5ogetLk3DIQRr+81I1k7uVOzqE2YfHgD3yESR4Fpje6p0BDQ9A/rMS4htxei97d/mMI0Y3OzsFwDZuCcBmH4ELOLJPTE8L9segia6LnC8knY3HwXNiajr5rEhuJ8HUU5PWMFn7EiRP/kWFvJPUCo8KPTVh9G6SPeRzMD2YDrnkiW3xyhWXBj7P2IMF1p+vJYj8q9GVov7LK3ELwpZ+FFElL9+mCaWFPnDx0yiiadwXzZcrVAiT14JuZgLgFz+AFYJjXsbWeFt9GscV4RtcozKAfIOy+FykgUR16dftzZAUT/weIuLw6ARa9HjEmI8hj5tX83V0NaMQN4LGX3tuxRoX+u4K1n1gytH/fE+jvdH5BvyY/mLaSpqBhfGKuZ5jJ8denNPPZuxO58hkR4iikQXElK2k7Mu1aVvqvL51Y="
    - # ^^ GPG_KEY_NAME
    - secure: "iTjvDz6y3ZbtBCl6+ahEnvz5uTOO6mWEg/an2JKmnx3o4mglUuBF0zOKQ3rLvoyft/N2TGqgV5tWDEJPN/2hisNYDLpIJZ2ZwB/79Rtg7gh0WUsCOVF/tcldPFZgLzTDo3sTRkjufKjBZNf7VEAtTePnxkjtB3HADLJl6ryYDrXJcQFaWsZJyFiyDd/3yz6H7EfMRfU83XkUvYWoL0Mf9BHSJLZQ4hNKQNox98lwGZxN2tqjqHQknXWrP1Rvbn50YeO+K8z86P+rOor7+0+HgpVfznTG+vDPfRL+gJGbiPugwxE6wiqiSs3p+Y2Yu0a9kFV+zmF/O2KRrwnL64MvlbsEk3E/lccwpa1cSII3WtzBqUI5aX1Bs9Pm8Kr1Hzj0JUqXxU8a0eAdHF6bxYDYE3tdyUyFDJO/urYTqIGlf9rhbraAWESF+Qu2YpTVK1nsh2RW3D0ED/qrRhOrYUcgv+DqUxCdkb0eMp2sNYLSsYrLlCf+WgFAuKPW5bMstI5uTyEox3gcbwPI/pGSz/l+3roR+fujbrRW7VVdpDnwtL6yt7frvRDQMAJXAuuS9eA47Dvcf4KuSPU3ldinmNLcJYhBLmK/vuLfWN5jdfoynMIzGOROINdpKUpt3HCBd97DoNzhopTYtE+r5uDS1mvpfkK+cWcPHFRP0BFCWWx7Z18="
    - # ^^ GPG_PASSPHRASE

sudo: required
services:
  - docker

before_install:
  - sudo apt-get update -qq
  - sudo apt-get -y -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confnew install docker-engine
  - env
# Pre-fetch docker images - seems to need to be done before docker env vars are set
  - docker pull richnorth/dynalite:latest
# Update env vars required by testcontainers
  - export DOCKER_HOST=tcp://127.0.0.1:2375
  - export DOCKER_TLS_VERIFY=0
  - env

install: mvn install -P !build-extras -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - mvn -B -P !build-extras test

deploy:
  provider: script
  script: release/deploy.sh
  on:
    tags: true
    branch: master

cache:
  directories:
    - '$HOME/.m2/repository'
