language: java
jdk:
  - oraclejdk8

env:
  global:
    - secure: "JA1XGliMbw370X96ukGrvnBDzYQxlOxUo/Scff4VQyq+7sdCCXTQpbjpl28kri08QPt0WS9qcLHnOmcZiq62YUIDuNQAk2kIoki/DO4M9b86UgOHLb5MTYDxYIbOCJlZdl3TUEd2tUIJ0xM7AIRe8kHXUNhNxEjsm+qab23OSK/gZrzLwcWhCQfenE9uedL9xUeJI5SorJ/F12X65f014bVsniym2QXlFiOWvRaZnGWCfYxU9xWl9wSastFCzMsUTGqeRXftp5kfof6Y6KtDbkUSBbcbHdb4wv4g14g7GYd4dkza4CelmKoLbV5H2xjMOzHR/6NDQ8azSv5j5TRD4uBcdBr5rBJSowWEymjw66ZhSTYYRfYYnE1cQhLrGVT2XoUPmCY5PzSYdRkCA/kZdnJPxb+wdMgfdx3FE67wHm6M7uWOW9Smdy+qwNx3T4Fdp75lrxkuLK6Thtk/fGhs1g4lEsXD+YXgIdZjnj8Go2GxdiEQCIJovJRWDkp6+C/BjS9nbVBHtZ36FR73NELV7R6dAZNmiXbrxI3YfqKTvIg6OGbiR7EQ8WATsnMmMtvRyPi1kEj8sulhtg95WkVjYkWUiERv8HTGbjpPZEVQ+q9+3CJzmwmcmImDS60eXAr84R011AkG/YccrP20x/27UlKO7PtGiu8a0awesAzQmVs="
    - # ^^ OSSRH_JIRA_USERNAME
    - secure: "kilIEz+jutUflyosc42CoxD1G9J9c1nYyXWnz3K3Z4BeYFb+y8YbYDjP1WmeCFVzFfjN8UuLQdMc74Z2QTVgQpFfFx0p6uQtBVR3uonKNZuIemeEz+c/ILEu7MAhOAoytoEnsNyx4foNyNqvFehHbe7JbIuh1jathBfnwHotvlxvE5GwetpvOAH/GkUFb8U8sIhlwhUGsVkPkB0EPBxO9MyzGMi7QqgdzprTKyDCZKBGJUqJ8hWJHwwxmO8XdLbPh/xiIe0/lj0rEiHRRMI84nuxdaq7kqg2ymvh8RF55yecuQbRz4dEPUMb42j+wzcNumF/0MyG29SCPwX3xQu9iLI5/nMTBB4yd939ejILXrdRk62dUkdQyqafcq1+BrsVOEeXEKEN7Yvz0WjiIhRMF5E3MwoQLyFqhZGW6JJ2sBvP2XSjpQ3NfKrq6yEzF6fkaU7eYG5m90UJzkmS26/S40HBATcYPkbhVB+NmmXfpk2ms17YJqY5B+giS1j59eUkq+WLrz49N062kzbtHIfDodopsYT0clxfa8qMX/a5MdC/Vg0OVmpgt8e5dVztIwSEgSw0Pxy9se020hp4S/p6FIGhvvhNS0r7NwFM/BISRxEWfq5SmntgE8MOhXChS2AUpE7e/2IE9Drf2HpEiE/K7lOALz5hSMyjDvDdMTP6KiQ="
    - # ^^ OSSRH_JIRA_PASSWORD
    - secure: "EZ13GZbX3SbJwoWh2I094n8VSB2hTTnq+SYziVSFnPAoRGfIOZNWB6O0HXUDiAlhsbdIWDtl/OCY6u5BflFqhBYtaXSZNg9V5N0TpWvy8vQsELkzl0ha6J8PXmeZyj82gYOS6wrHCqQMnnfKwfJ/h0V+b+EqrjvR5q7KY/DzCfGNStRJykjpf5JYZFfJqOmvQIHOkMtRm2xtnqoM1VxTxgFI2R0xiOVyvqNBPLBsU+lOJxiyFxym+jquuUddmjZ/NM+yOj0yfW6HoOA8drF0jXvoM2k9N3laL+Ll17YZDWRcgrRZdpjWvYTegaFTB+NP2Ff/yitQDRvl5WCMG91W+RdYDNdtsFP5xSHpQj1VgclEXzdpnxijGvewhAAAo32KXuI+JS4cdMzh5NNw2+i0bYuXJNaFZd6Rb64k4Aq0CKYk0th3kLdk09EFVoCEuT8IIFf5ELtT8DJiNMUKJww2sXD1eZzaPUIXkT3holGAxLwRhhRcdlsodRJ8Smbn6ueY8+mIUlIX1NJQUoBpXFvX7QS6tBJRh0O2PAUDjYPFhbcIL6gs7KGC29F5PjjMNslxfevEtIy8HaCuVsdAU8dxGp8XiVh/qLlGgJnynUgY97pzI7G4d21tuMJV8pJdNsXIA/9f7TLwoxgaltSbLn8TIEa9qTaswyc5RYnzQ/R8mss="
    - # ^^ GPG_KEY_NAME
    - secure: "mi4uCFmcYV5wkqbhbC8UOLNwUUcnMpk841V7WqyAbqQLfQ352N5mgzCiJx2RvVHUSbj+bLBGYQqj0WPM3q8nRwsTLwHAkL/qQLh7dmNW+wo3IVgw01cQMj01/bpKtscFEfc0DsfI8F4ozYIMM9BSrRK5O+5XXibFxk+F6wL+w7ZK/bt61DhGehjf7LTbzBcZohPBQzunUgkb30htEcf4aVl0XPxp/kXtHzrA42J1sWJVciKohoeFgcqoqa51W4rLOJrBZAm6BRRAX+7SfKB1DpgXVACRgHjS1WNGvOkiYyK86xF3xQu3lEfSR8HFQoaWaNmfFwDZ8KhdgSeW9N+OV6B4uupbg7Q4HNs7+5uNj6a2ThGGeCgZlEx0JFLCYDs0ZF5hDGo9oIfNcjvfzAubl44UlO0W7a633w0QsRqijOaqJ6IAgk/OEuVYmSgMvNXwGV9i30ajghE2owJS9J3jDlQ8++SWRbbyxUOeg4sLm42w0UdKSztRvek1AK5hhLYn/5gwWAMazKgf2hFBES6K7y/qVJhd3hGt4aiovC72wOJdkrwKQJsOd0BPksxBI5d6H3+hOniH8A5J8foZNOkBEPcbJ1r23NxNVfwS+jzldVP1MOyCSMDetUB+UkiXfXQR7ql8HPQY6Ltr4zO++qvKCIXSL8UR0CIlpOP6w+kcQvM="
    - # ^^ GPG_PASSPHRASE

sudo: required
services:
  - docker

install: ./mvnw install -P !build-extras -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - ./mvnw -B -P !build-extras test

deploy:
  sudo: false
  services: []
  provider: script
  script: release/deploy.sh
  on:
    tags: true
    branch: master

cache:
  directories:
    - '$HOME/.m2/repository'
